server:
  port: 8080

spring:
  application:
    name: REST API FOR COLLECTORS

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    default-schema: collector
    liquibase-schema: collector

  redis:
    host: ${SPRING_DATA_REDIS_HOST}
    port: 6379
    password: ${SPRING_DATA_REDIS_PASSWORD}
    timeout: 7000ms
    lettuce:
      pool:
        max-active: 5
        max-idle: 4
        min-idle: 0
        max-wait: 5000ms

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

  minio:
    url: ${SPRING_MINIO_URL}
    access-key: ${SPRING_MINIO_ACCESS_KEY}
    secret-key: ${SPRING_MINIO_SECRET_KEY}
    bucket: ${SPRING_MINIO_BUCKET}

logging:
  level:
    org.springframework: DEBUG
    org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: DEBUG
    org.liquibase: INFO
    controller: DEBUG
    ru.pozhar.collector_api: DEBUG

  file:
    name: logs/collector-api.log
    max-size: 10MB
    max-history: 30

  pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true