apiVersion: v1
kind: Service
metadata:
  name: collector-api
  labels:
    app: collector-api
spec:
  selector:
    app: collector-api
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30004
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-api
  labels:
    app: collector-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector-api
  template:
    metadata:
      labels:
        app: collector-api
    spec:
      containers:
        - name: collector-api
          image: collector-api
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/Collector%20DB"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              value: "redis"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_MINIO_URL
              value: "http://minio:9000"
            - name: SPRING_MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: SPRING_MINIO_SECRET_KEY
              value: "minioadmin"
            - name: SPRING_MINIO_BUCKET
              value: "collector-bucket"
            - name: LOGGING_LEVEL_ROOT
              value: "INFO"
            - name: LOGGING_LEVEL_SPRING
              value: "DEBUG"
            - name: LOGGING_LEVEL_HIBERNATE_SQL
              value: "DEBUG"
            - name: LOGGING_LEVEL_HIBERNATE_BIND
              value: "DEBUG"
            - name: LOGGING_LEVEL_LIQUIBASE
              value: "INFO"
            - name: LOGGING_LEVEL_MINIO
              value: "DEBUG"
            - name: LOGGING_LEVEL_CONTROLLER
              value: "DEBUG"
            - name: LOGGING_LEVEL_APP
              value: "DEBUG"
            - name: LOGGING_FILE_NAME
              value: "logs/collector-api.log"
            - name: LOGGING_FILE_MAX_SIZE
              value: "10MB"
            - name: LOGGING_FILE_MAX_HISTORY
              value: "30"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15