ALTER SYSTEM SET max_connections = 200;
CREATE DATABASE "Camunda DB";
CREATE USER "user" WITH ENCRYPTED PASSWORD 'password';
ALTER DATABASE "Camunda DB" OWNER TO "user";
GRANT ALL PRIVILEGES ON DATABASE "Camunda DB" TO "user";