apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
spec:
  selector:
    app: notification
  ports:
    - name: "8080"
      protocol: TCP
      port: 8080
    - name: "5005"
      protocol: TCP
      port: 5005
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: notification
          ports:
            - containerPort: 8080
            - containerPort: 5005
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USER
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
            - name: LOGGING_LEVEL_ROOT
              value: "INFO"
            - name: LOGGING_LEVEL_SPRING
              value: "DEBUG"
            - name: LOGGING_LEVEL_APP
              value: "DEBUG"
            - name: LOGGING_FILE_NAME
              value: "logs/notification.log"
            - name: LOGGING_FILE_MAX_SIZE
              value: "10MB"
            - name: LOGGING_FILE_MAX_HISTORY
              value: "10"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 30
            failureThreshold: 10